[workspace]
members = [
	"examples/async-sqlite",
	"examples/cpu-count",
	"examples/gzip-stream",
	"examples/hello-world",
	"examples/tokio-fetch",
    "examples/tokio-callback",
]

[profile.release]
lto = true

[patch.crates-io]
neon = { git = "https://github.com/neon-bindings/neon.git" }
