[package]
name = "cpu-count"
version = "0.1.0"
description = "CPU Count"
license = "MIT"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "1"
num_cpus = "1"
